<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a1c89d65-93ab-467b-8337-1d6866a7a965</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Modules.Cart\ECommerce.Modules.Cart.csproj" />
    <ProjectReference Include="..\ECommerce.Modules.Catalog\ECommerce.Modules.Catalog.csproj" />
    <ProjectReference Include="..\ECommerce.Modules.Identity\ECommerce.Modules.Identity.csproj" />
  </ItemGroup>

</Project>
